# The Site Configuration
#
# The following values are used to configure the site.
# For more options, see: https://jekyllrb.com/docs/configuration/

title: I'm Vlad you're here
description: >-
  Music, puns, and software engineering.
tagline: Music, puns, and software engineering.
author: Vlad Stoian
email: smile@vlad.blog
url: "https://vlads.page"
baseurl: ""

# Theme Settings
theme: jekyll-theme-chirpy

# Language & Timezone
lang: en
timezone: UTC

# Social Accounts (Chirpy specific)
social:
  name: Vlad Stoian
  email: smile@vlad.blog
  links:
    - https://twitter.com/vladstoian
    - https://github.com/vlad-stoian
    - https://linkedin.com/in/vladstoian

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-feed

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Archives
archives:
  enabled: [categories, tags]
  layouts:
    category: archives-category
    tag: archives-tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Chirpy Specifics
avatar: /assets/img/avatar.png  # Placeholder, user should update this
google_analytics:
  # id:
  # google_tag_manager:

disqus:
  # shortname:

collections:
  tabs:
    output: true
    sort_by: order
